# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Thousand-Test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Thousand-Test
	pod 'Alamofire', '~> 4.8.2'
	pod 'DZNEmptyDataSet'
	pod 'RxSwift'
	pod 'SnapKit'
	pod 'SVProgressHUD'
	pod 'RealmSwift'

  target 'Thousand-TestTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
